server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:hsql://localhost/logdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.HSQLDialect
    show-sql: false

logging:
  level:
    org.springframework: INFO
    com.creditsuisse: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: app.log

logfile:
  location: /home/manoj-2/logs
  name: logfile.txt


